version: "2.1"

services:
  tuleap:
    image: enalean/tuleap-aio
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: "${VIRTUAL_HOST:-localhost}"
      DB_HOST: "db"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-ChangeMe}"
    volumes:
      - tuleap-data:/data
#      - ~/workspace/tuleap:/usr/share/tuleap
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db

  db:
    image: mysql:5.6
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
      - ./sql_mode.cnf:/etc/mysql/conf.d/sql_mode.cnf
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-ChangeMe}"

volumes:
  db-data:
  tuleap-data:
